# Compile project on Ubuntu
name: Run Cuda install Ubuntu
runs:
    using: composite
    steps:
    - name: Install CUDA
      run: |
        wget https://raw.githubusercontent.com/KonduitAI/cuda-install/master/.github/actions/install-cuda-ubuntu/install_cuda_ubuntu.sh
        chmod +x ./install_cuda_ubuntu.sh
        ./install_cuda_ubuntu.sh
        CUDA_VERSION_MAJOR_MINOR=${cuda}
        # Split the version.
        # We (might/probably) don't know PATCH at this point - it depends which version gets installed.
        export CUDA_MAJOR=$(echo "${CUDA_VERSION_MAJOR_MINOR}" | cut -d. -f1)
        export CUDA_MINOR=$(echo "${CUDA_VERSION_MAJOR_MINOR}" | cut -d. -f2)
        export CUDA_PATCH=$(echo "${CUDA_VERSION_MAJOR_MINOR}" | cut -d. -f3)
        # Set paths for subsequent steps, using ${CUDA_PATH}
        echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
        CUDA_PATH_RESOLVED="/usr/local/cuda-${CUDA_MAJOR}.${CUDA_MINOR}"
        echo "CUDA_PATH=${CUDA_PATH_RESOLVED}" >> $GITHUB_ENV
        echo "${CUDA_PATH_RESOLVED}/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${CUDA_PATH_RESOLVED}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        echo "Added CUDA path ${CUDA_PATH_RESOLVED} and updated LD_LIBRARY_PATH"
      

      shell: bash

    # Specify the correct host compilers
    - name: Install/Select gcc and g++
      shell: bash
      run: |
        sudo apt-get install -y gcc-${{ env.GCC }} g++-${{ env.GCC }}
        echo "CC=/usr/bin/gcc-${{ env.GCC }}" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-${{ env.GCC }}" >> $GITHUB_ENV
        echo "CUDAHOSTCXX=/usr/bin/g++-${{ env.GCC }}" >> $GITHUB_ENV
        sudo apt-get clean
        sudo apt-get autoclean
